SELECT TO_CHAR(TO_DATE('01-NOV-2022','DD-MON-YYYY') + ROWNUM -1, 'DD/MM/YYYY')  Data,
       TO_CHAR(TO_DATE('01-NOV-2022','DD-MON-YYYY') + ROWNUM -1, 'WW') SemanaMes
   FROM dba_tables
   WHERE ROWNUM <= 
   TO_DATE('30-NOV-2022','DD-MON-YYYY')-TO_DATE('01-NOV-2022','DD-MON-YYYY')+1;
